#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════
#  PAI Fork Install — Lars Boes
#  Sets up Pi + PAI on a fresh machine
#
#  Usage: curl -fsSL https://raw.githubusercontent.com/larsboes/PAI/dev/install.sh | bash
#    or:  bash install.sh
# ═══════════════════════════════════════════════════════════
set -euo pipefail

# ── Colors ──────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[0;33m'; RED='\033[0;31m'; BLUE='\033[0;34m'; RESET='\033[0m'; BOLD='\033[1m'
ok()   { echo -e "  ${GREEN}✓${RESET} $1"; }
info() { echo -e "  ${BLUE}ℹ${RESET} $1"; }
warn() { echo -e "  ${YELLOW}⚠${RESET} $1"; }
fail() { echo -e "  ${RED}✗${RESET} $1"; exit 1; }
header() { echo -e "\n${BOLD}${BLUE}── $1 ──────────────────────────────────────────${RESET}"; }

# ── Config ──────────────────────────────────────────────────
PAI_DIR="${PAI_DIR:-$HOME/Developer/PAI}"
PAI_WORK_DIR="${PAI_WORK_DIR:-$HOME/Developer/pai-work}"
PAI_REPO="${PAI_REPO:-https://github.com/larsboes/PAI.git}"
PAI_BRANCH="${PAI_BRANCH:-dev}"
PI_CONFIG="$HOME/.pi/agent/config.yml"

# ── Banner ──────────────────────────────────────────────────
echo ""
echo -e "${BOLD}  PAI × Pi — Personal AI Infrastructure${RESET}"
echo -e "  Lars Boes fork — github.com/larsboes/PAI"
echo ""

# ════════════════════════════════════════════════════════════
header "1. Prerequisites"

# Bun
if command -v bun &>/dev/null; then
  ok "bun $(bun --version)"
else
  warn "bun not found — installing..."
  curl -fsSL https://bun.sh/install | bash
  export PATH="$HOME/.bun/bin:$PATH"
  ok "bun installed"
fi

# Git
command -v git &>/dev/null && ok "git $(git --version | cut -d' ' -f3)" || fail "git not found — install git first"

# Pi
if command -v pi &>/dev/null; then
  ok "pi already installed"
else
  info "Installing Pi coding agent..."
  npm install -g @mariozechner/pi-coding-agent 2>/dev/null || \
    bun install -g @mariozechner/pi-coding-agent
  ok "pi installed"
fi

# ════════════════════════════════════════════════════════════
header "2. Clone PAI fork"

if [ -d "$PAI_DIR/.git" ]; then
  info "PAI already cloned at $PAI_DIR — pulling latest..."
  git -C "$PAI_DIR" fetch origin
  git -C "$PAI_DIR" checkout "$PAI_BRANCH"
  git -C "$PAI_DIR" pull origin "$PAI_BRANCH"
  ok "PAI up to date (branch: $PAI_BRANCH)"
else
  info "Cloning larsboes/PAI → $PAI_DIR ..."
  mkdir -p "$(dirname "$PAI_DIR")"
  git clone --branch "$PAI_BRANCH" "$PAI_REPO" "$PAI_DIR"
  ok "PAI cloned"
fi

# ════════════════════════════════════════════════════════════
header "3. pai-work (private work packs)"

if [ -d "$PAI_WORK_DIR/.git" ]; then
  ok "pai-work already at $PAI_WORK_DIR"
else
  warn "pai-work not found at $PAI_WORK_DIR"
  info "pai-work is a private repo — clone it manually if needed:"
  echo "    git clone <your-pai-work-repo> $PAI_WORK_DIR"
fi

# ════════════════════════════════════════════════════════════
header "4. Pi config (~/.pi/agent/config.yml)"

mkdir -p "$(dirname "$PI_CONFIG")"

if [ -f "$PI_CONFIG" ]; then
  # Check if PAI/Packs already referenced
  if grep -q "PAI/Packs" "$PI_CONFIG"; then
    ok "config.yml already references PAI/Packs"
  else
    warn "config.yml exists but doesn't reference PAI/Packs — appending skills config..."
    cat >> "$PI_CONFIG" << 'YAML'

skills:
  customDirectories:
    - ~/Developer/PAI/Packs
    - ~/Developer/pai-work/Packs
YAML
    ok "config.yml updated"
  fi
else
  info "Creating ~/.pi/agent/config.yml ..."
  cat > "$PI_CONFIG" << 'YAML'
# Pi Agent Configuration
# Generated by PAI fork install script

skills:
  customDirectories:
    - ~/Developer/PAI/Packs
    - ~/Developer/pai-work/Packs

defaultThinkingLevel: high

# Set your model — examples:
# modelRoles:
#   default: anthropic/claude-sonnet-4-5
#   smol: anthropic/claude-haiku-4-5
#
# For Amazon Bedrock:
# modelRoles:
#   default: amazon-bedrock/eu.anthropic.claude-sonnet-4-6
YAML
  ok "config.yml created at $PI_CONFIG"
  warn "Edit $PI_CONFIG to set your model provider!"
fi

# ════════════════════════════════════════════════════════════
header "5. agent-browser"

if command -v agent-browser &>/dev/null; then
  ok "agent-browser $(agent-browser --version 2>&1 | head -1)"
else
  info "Installing agent-browser (browser automation CLI)..."
  # Use npm via Artifactory if configured, else bun
  if npm config get registry 2>/dev/null | grep -q "artifactory"; then
    npm install -g agent-browser
  else
    bun install -g agent-browser
  fi
  ok "agent-browser installed"
  info "Chrome auto-detected from system — no 'agent-browser install' needed if Chrome is present"
  if ! command -v google-chrome &>/dev/null && ! command -v chromium &>/dev/null; then
    warn "Chrome not found — run 'agent-browser install' to download it"
  fi
fi

# ════════════════════════════════════════════════════════════
header "6. Verify"

echo ""
echo -e "  ${BOLD}PAI Packs:${RESET}"
SKILL_COUNT=$(find "$PAI_DIR/Packs" -name "SKILL.md" 2>/dev/null | wc -l)
ok "$SKILL_COUNT skills found in $PAI_DIR/Packs"

if [ -d "$PAI_WORK_DIR/Packs" ]; then
  WORK_COUNT=$(find "$PAI_WORK_DIR/Packs" -name "SKILL.md" 2>/dev/null | wc -l)
  ok "$WORK_COUNT work skills found in $PAI_WORK_DIR/Packs"
fi

echo ""
echo -e "  ${BOLD}Next steps:${RESET}"
echo -e "  1. Set your model in ${BLUE}$PI_CONFIG${RESET}"
echo -e "  2. Run ${BOLD}pi${RESET} to start"
echo -e "  3. Try: ${BOLD}what skills do you have?${RESET}"
echo ""
ok "PAI fork install complete 🎉"
