#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════
#  sync-ignore.sh — Generate Packs/.ignore from skills.yaml
#
#  Pi's skill loader respects .ignore files (same as .gitignore format).
#  This script generates Packs/.ignore to exclude inactive packs
#  from pi's recursive SKILL.md scan.
#
#  Usage:
#    ./sync-ignore.sh           # regenerate Packs/.ignore
#    ./sync-ignore.sh --show    # print what would be ignored
# ═══════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PACKS_DIR="$SCRIPT_DIR/Packs"
SKILLS_YAML="$SCRIPT_DIR/skills.yaml"
IGNORE_FILE="$PACKS_DIR/.ignore"

SHOW_ONLY=false
[[ "${1:-}" == "--show" ]] && SHOW_ONLY=true

# Parse active skills from skills.yaml
parse_active_skills() {
  sed -n '/^active:/,/^[a-z]/{/^  - /p}' "$SKILLS_YAML" | sed 's/^  - //'
}

# Get all pack directories
ALL_PACKS=$(find "$PACKS_DIR" -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | sort)
ACTIVE_PACKS=$(parse_active_skills | sort)

# Find inactive packs (in ALL but not in ACTIVE)
INACTIVE=$(comm -23 <(echo "$ALL_PACKS") <(echo "$ACTIVE_PACKS"))

INACTIVE_COUNT=$(echo "$INACTIVE" | grep -c "." || true)
ACTIVE_COUNT=$(echo "$ACTIVE_PACKS" | grep -c "." || true)

if $SHOW_ONLY; then
  echo "Active: $ACTIVE_COUNT packs"
  echo "Ignored: $INACTIVE_COUNT packs"
  echo ""
  echo "Would ignore:"
  echo "$INACTIVE" | sed 's/^/  /'
  exit 0
fi

# Generate .ignore file
cat > "$IGNORE_FILE" << 'HEADER'
# Auto-generated by sync-ignore.sh — do not edit manually
# Packs listed here are excluded from pi's recursive SKILL.md scan.
# Regenerate with: ./sync-ignore.sh
#
# To activate a pack: add it to skills.yaml, then re-run this script.
HEADER

echo "" >> "$IGNORE_FILE"
echo "$INACTIVE" | while IFS= read -r pack; do
  [[ -z "$pack" ]] && continue
  echo "$pack/" >> "$IGNORE_FILE"
done

echo "Generated $IGNORE_FILE ($INACTIVE_COUNT packs ignored, $ACTIVE_COUNT active)"
