#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════
#  generate-inventory — Walk Packs/ and emit Packs/INVENTORY.md
#
#  For each pack:
#    - source: upstream | fork-only | hybrid
#    - manifested: yes/no (which files)
#    - skill files: count
#    - workflow files: count
#    - last-touched local / last-touched upstream
#    - customized: bool (any local file differs from upstream)
#
#  Generated table is committed. Never hand-edited.
# ═══════════════════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FORK_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_DIR="$(cd "$FORK_DIR/.." && pwd)"
MANIFEST="$FORK_DIR/manifest.yaml"
EXCLUSIONS="$FORK_DIR/exclusions.yaml"
OUTPUT="$REPO_DIR/Packs/INVENTORY.md"

cd "$REPO_DIR"

# Ensure upstream is fetchable
if ! git remote get-url upstream >/dev/null 2>&1; then
  echo "Error: 'upstream' remote not configured" >&2
  exit 1
fi

# Build set of upstream pack names
mapfile -t UPSTREAM_PACKS < <(git ls-tree upstream/main Packs/ 2>/dev/null \
  | awk '$2=="tree" {print $4}' \
  | sed 's|Packs/||' \
  | sort)

# Build set of local pack names
mapfile -t LOCAL_PACKS < <(find Packs -maxdepth 1 -mindepth 1 -type d -printf '%f\n' | sort)

# Manifest paths (for "manifested" column)
read_manifest() {
  grep -E '^\s*-\s*path:' "$MANIFEST" 2>/dev/null \
    | sed -E 's/^\s*-\s*path:\s*//;s/\s*$//' | sort -u
}
mapfile -t MANIFEST_PATHS < <(read_manifest)

is_in_manifest() {
  local p="$1"
  printf '%s\n' "${MANIFEST_PATHS[@]}" | grep -qxF "$p"
}

is_upstream_pack() {
  local p="$1"
  printf '%s\n' "${UPSTREAM_PACKS[@]}" | grep -qxF "$p"
}

# Count files in a pack
count_files() {
  local pack="$1" pattern="$2"
  find "Packs/$pack" -name "$pattern" 2>/dev/null | wc -l
}

# Last commit touching a path
last_local_change() {
  git log -1 --format='%cs' -- "$1" 2>/dev/null || echo "—"
}

last_upstream_change() {
  git log upstream/main -1 --format='%cs' -- "$1" 2>/dev/null || echo "—"
}

# Check if any file in a pack differs from upstream
pack_has_drift() {
  local pack="$1"
  is_upstream_pack "$pack" || return 1
  # Compare git tree SHAs — fast and exact
  local local_tree upstream_tree
  local_tree="$(git rev-parse "HEAD:Packs/$pack" 2>/dev/null || echo "")"
  upstream_tree="$(git rev-parse "upstream/main:Packs/$pack" 2>/dev/null || echo "")"
  [[ -n "$local_tree" && "$local_tree" != "$upstream_tree" ]]
}

# Count manifested files within a pack
pack_manifest_count() {
  local pack="$1" count=0
  for p in "${MANIFEST_PATHS[@]}"; do
    [[ "$p" == "Packs/$pack/"* ]] && ((count++)) || true
  done
  echo "$count"
}

# ── Generate ────────────────────────────────────────────────────────────
{
  echo "# Pack Inventory"
  echo
  echo "> Auto-generated by \`.pai-fork/tools/generate-inventory.sh\` — do not edit manually."
  echo "> Run on every commit by pre-commit hook. Last generated: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  echo
  echo "## Summary"
  echo
  local_count="${#LOCAL_PACKS[@]}"
  upstream_count="${#UPSTREAM_PACKS[@]}"
  fork_only_count=0
  drifted_count=0
  for p in "${LOCAL_PACKS[@]}"; do
    is_upstream_pack "$p" || ((fork_only_count++)) || true
    pack_has_drift "$p" 2>/dev/null && ((drifted_count++)) || true
  done

  echo "- **Local packs:** $local_count"
  echo "- **Upstream packs:** $upstream_count"
  echo "- **Fork-only packs:** $fork_only_count"
  echo "- **Drifted from upstream:** $drifted_count"
  echo "- **Manifest entries:** ${#MANIFEST_PATHS[@]}"
  echo
  echo "## Packs"
  echo
  echo "| Pack | Source | Drift | Manifested | SKILL.md | Workflows | Last local | Last upstream |"
  echo "|---|---|---|---|---|---|---|---|"

  for pack in "${LOCAL_PACKS[@]}"; do
    [[ -d "Packs/$pack" ]] || continue

    if is_upstream_pack "$pack"; then
      source="upstream"
      if pack_has_drift "$pack"; then
        drift="🟡 yes"
      else
        drift="✅ clean"
      fi
    else
      source="**fork-only**"
      drift="—"
    fi

    mcount=$(pack_manifest_count "$pack")
    [[ $mcount -gt 0 ]] && manifest="✅ $mcount" || manifest="—"

    skill_count=$(count_files "$pack" "SKILL.md")
    workflow_count=$(count_files "$pack" "*.md" | head -1)
    workflow_dir="Packs/$pack/Workflows"
    [[ -d "$workflow_dir" ]] && workflow_count=$(find "$workflow_dir" -name "*.md" 2>/dev/null | wc -l) || workflow_count=0

    last_local=$(last_local_change "Packs/$pack")
    if is_upstream_pack "$pack"; then
      last_upstream=$(last_upstream_change "Packs/$pack")
    else
      last_upstream="—"
    fi

    echo "| $pack | $source | $drift | $manifest | $skill_count | $workflow_count | $last_local | $last_upstream |"
  done

  echo
  echo "## Legend"
  echo
  echo "- **Source:** \`upstream\` = exists in Daniel's repo · \`fork-only\` = unique to this fork"
  echo "- **Drift:** \`🟡 yes\` = at least one file in pack differs from upstream · \`✅ clean\` = identical to upstream"
  echo "- **Manifested:** count of files declared in \`.pai-fork/manifest.yaml\` (= \"intentional customization\")"
  echo
  echo "## Notes"
  echo
  echo "- **Why \"drift\" is high:** During May 2026 restructure, our fork flattened packs (\`Packs/Foo/SKILL.md\`)"
  echo "  while Daniel later moved them into \`Packs/Foo/src/SKILL.md\`. Pure renames — content identical, but tree"
  echo "  SHAs differ. \`sync.sh\` handles this correctly via git's rename detection (R100 status)."
  echo "- **Drift without manifest entries** that ISN'T a pure rename = silent local edits. Add via"
  echo "  \`.pai-fork/tools/add-customization.sh\`."
} > "$OUTPUT"

echo "✓ Wrote $OUTPUT"
echo "  Local packs:    ${#LOCAL_PACKS[@]}"
echo "  Upstream packs: ${#UPSTREAM_PACKS[@]}"
echo "  Drifted:        $drifted_count"
